### ISSUE TITLE
Category & tags don't persist on plugin creation

### ISSUE THREAD

**Issue by m1foley** [vim-awesome/vim-awesome#145]
Plugin URL: http://vimawesome.com/plugin/expresso-vim

When I first created this plugin entry, I placed it in the "Commands" category, and gave it the "Math" tag. Neither of these were persisted when the plugin was added to vim-awesome; I had to manually re-add both the category & tags.

I don't know if #142 fixed the tags portion of this.

**Comment by captbaritone** [comment]
@m1foley I believe this is actually because we discovered your plugin from vim.org rather than from your submisssion.

We scraped your plugin at Wed, 30 Mar 2016 00:00:00 GMT, and you didn't submit it until nearly 24 hours later: Wed, 30 Mar 2016 23:22:28 GMT.

At this point we don't have any facility for merging submissions with scrapped plugins. We probably should.
