### ISSUE TITLE
[unresolved] All plugins show updated 4 months ago ?!

### ISSUE THREAD

**Issue by wifiextender** [vim-awesome/vim-awesome#227]
Regardless of the clicked plugin link, your website will always show updated 4 months ago.

![untitled](https://cloud.githubusercontent.com/assets/4725121/16714350/24a4e04e-46c0-11e6-8261-1fb8956e4d28.png)

**Comment by wifiextender** [comment]
Closing this issue as unresolvable. Feel free to update it when you resolve it.

**Comment by captbaritone** [comment]
I think this may be a legitimate issue, so I'm going to reopen. I see several plugins with "last modified" dates greater than 4 months, but none less than 4 months (despite them having github updates more recent than that).

Is that what you were noticing?

**Comment by captbaritone** [comment]
It looks like our GitHub plugin scrape task has been broken for a while due to #96. I'm currently shipping #229 in an attempt to resolve that issue. The task appears to be running smoothy now, but it may take a few days for those results to get fully up to date, and be reflected on the website.

Thanks for the report.

**Comment by captbaritone** [comment]
This issue seems to be resolved. Thanks again to @wifiextender for bringing it to my attention!

http://vimawesome.com/plugin/vim-airline
