### ISSUE TITLE
Add wishlist/lazyweb area

### ISSUE THREAD

**Issue by grr** [vim-awesome/vim-awesome#346]
I'm not aware of any place where users can submit _ideas_ for new plugins. It would be great if we could have a curated list of unimplemented plugin requests that users can vote on. Then the minority of users who are actually proficient in vimscript, will know what project to tackle next, if they're so inclined.

**Comment by captbaritone** [comment]
Sounds like this feature would require some active moderation and judgement calls, I'm not sure I personally have the time/interest to moderate such a feature. Did you have any specific ideas as to how this feature would be implemented? Would you be interested in implanting the feature yourself?

**Comment by grr** [comment]
I have no idea how to implement (consider that my first wishlist item ;-), but I was thinking that the section would be maintained solely by users. They submit the items, and other users vote them up/down or comment (links to vim wiki or stackoverflow, etc). So moderation would only be necessary if items were flagged as inappropriate/spam/etc.

**Comment by captbaritone** [comment]
I don't currently have the time to work on such a feature, but it does sound interesting. I'm going to close this issue, since I don't see it having any immediate momentum. If other people express their interest in this feature, or if somebody wants to take it on as a project, I'm happy to re-evaluate.
