### ISSUE TITLE
What happened to the server?

### ISSUE THREAD

**Issue by TornaxO7** [vim-awesome/vim-awesome#396]
What happended to the server? I can't ping `vimawesome.com` anymore.

**Comment by GerardoGR** [comment]
Maybe the server crashed and it is one of those instances that @captbaritone might be able to restart it? (As mentioned in https://github.com/vim-awesome/vim-awesome/issues/390#issuecomment-572184731)

**Comment by vyavdoshenko** [comment]
whois response:

   Domain Name: VIMAWESOME.COM
   Registry Domain ID: 1813556997_DOMAIN_COM-VRSN
   Registrar WHOIS Server: whois.namecheap.com
   Registrar URL: http://www.namecheap.com
   Updated Date: 2021-07-08T07:43:38Z
   Creation Date: 2013-07-08T00:22:54Z
   Registry Expiry Date: 2022-07-08T00:22:54Z
   Registrar: NameCheap, Inc.
   Registrar IANA ID: 1068
   Registrar Abuse Contact Email: abuse@namecheap.com
   Registrar Abuse Contact Phone: +1.6613102107
   Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
   Name Server: DNS101.REGISTRAR-SERVERS.COM
   Name Server: DNS102.REGISTRAR-SERVERS.COM
   DNSSEC: unsigned
   
   It seems the record was updated yesterday. Maybe the domain name was lost.

**Comment by captbaritone** [comment]
I'm not sure who owns (owned?) the domain. Maybe @sophiebits?

**Comment by technikhil314** [comment]
Hey awesome folks who are maintaining it, 
Thanks a lot for all the work you have put up. 
I would like to understand and help in fixing the issue. 
Please let me know. I still see the site is down.

**Comment by vyavdoshenko** [comment]
I wrote an email to Jordan (captbaritone).  He answered, but as he answered that, he is not sure who held the domain.
I wrote to Sophie (sophiebits), but she doesn't answer. I don't know what to do else.

**Comment by closingin** [comment]
Hello guys,

If you want to access the website, it still answers at `198.58.101.18`, so you can edit your hosts file to resolve it on your machine. I found the IP address by [watching the IP history](https://viewdns.info/iphistory/?domain=vimawesome.com) of the domain. :slightly_smiling_face: 

```
# /etc/hosts
198.58.101.18 vimawesome.com
```

EDIT: I registered https://vimaweso.me/ (you'll encounter an ssl warning) and pointed it to their server, so that you can access the website without any system change. I contacted Jordan, David and Sophie to ask them to add this domain to the trusted ones, I'll keep you posted when they'll reply.

**Comment by sophiebits** [comment]
Hmm. I don't think I have the domain – best guess from my emails is that @divad12 registered it originally. I'll ping him separately in case he isn't checking GitHub notifications.

**Comment by captbaritone** [comment]
Site seems back up for me.

**Comment by sophiebits** [comment]
@divad12 and I were able to renew the domain last night for another 5 years. It's also been adjusted so that we both have access to manage the domain, which will hopefully avoid future outages. It's our plan to continue to keep the site online.

Thanks everyone here for flagging this – especially @TornaxO7 for filing and @closingin for the email (@vyavdoshenko, I don't seem to have ever received your message).

**Comment by vyavdoshenko** [comment]
@sophiebits I found your contact email address at your github profile. It seems my email can be marked as spam. Anyway it's awesome that vimawesome.com is back.
