### ISSUE TITLE
List all plugins by same author

### ISSUE THREAD

**Issue by Delapouite** [vim-awesome/vim-awesome#90]
Hello

Currently, the author of each plugin is displayed right after the plugin's name. Example : 

```
surround.vim by Tim Pope      3424  13559
surround.vim: quoting/parenthesizing made simple
```

What about adding a link on "Tim Pope" with `http://vimawesome.com/?q=tim%20pope` as the href.
This way a user can quickly see all Tim Pope plugins listed on the website.

**Comment by jonafato** [comment]
If GitHub `username/repo` combinations become the unique identifier (see #84), this could simply be `/plugins/username/repo` (or, to futureproof this and allow for other sites, `/plugins/github/username/repo`), with lists at just `/plugins/username` right? I don't think the fact that all of the vimorg plugins are listed under `vim-scripts` detracts from the value of being able to browse plugins listed at `/plugins/tpope` and `/plugins/Shougo`. There would also be plugins listed at `/plugins/vim-scripts`, but is there any harm in that?

**Comment by captbaritone** [comment]
@jonafato That seems quite reasonable. It would just be a matter of knowing what to call that link. "Author" would not really be appropriate.

**Comment by jonafato** [comment]
"Author" does seem like an awkward name here, especially because that field can map to both individuals and GitHub organizations. "Owner" or "Maintainer" are probably closer, but they still don't seem to fit right to me. This may be a moot point, though; will we actually be using this wording anywhere, or would it be similar to the breadcrumbs style links used on GitHub itself (e.g., for this repository, the `divad12` and `vim-awesome` are both links)?
